### ISSUE TITLE
Minkowski distance code is incorrect?

### ISSUE THREAD

**Issue by kamileyagci** [learn-co-curriculum/dsc-distance-metrics#1]
## Link to Canvas

https://learning.flatironschool.com/courses/1889/assignments/126252?module_item_id=261639

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
Incorrect Minkowski distance code:
# Manhattan Distance is the sum of all side lengths to the first power
manhattan_distance = np.power((length_side_1 + length_side_2 + ... length_side_n)**1 , 1/1) 

# Euclidean Distance is the square root of the sum of all side lengths to the second power
euclidean_distance = np.power((length_side_1 + length_side_2 + ... length_side_n)**2, 1/2)

# Minkowski Distance with a value of 3 would be the cube root of the sum of all side lengths to the third power
minkowski_distance_3 = np.power((length_side_1 + length_side_2 + ... length_side_n)**3, 1/3)

# Minkowski Distance with a value of 5
minkowski_distance_5 = np.power((length_side_1 + length_side_2 + ... length_side_n)**5, 1/5)

```

### Concern

Each length_side should have exponent first, then summed.

## What OS Are You Using?

- [ x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
Thanks for opening this @kamileyagci :wave:. I have updated the lesson so that the lengths of each side are raised to the correct power before summation with commit 46551dd8bcf5226a548975f09d10c5373aae985d. 

I am closing this issue at this time.
