### ISSUE TITLE
Confusing typo in Manhattan distance

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-distance-metrics#2]
## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
"the distance is the for the red, blue, and yellow lines."
```

### Concern

Seems to be a typo, but can be confusing for someone new to the material. I think it's supposed say:
the distance is the **same** for the red, blue, and yellow lines

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
Thanks for opening this issue @zshoorbajee :wave:. I have added the change to clarify that the three colored lines are indeed the same distances with commit 22494f992a9c470b7891cd097e7d715e530f6f6c. 

I am closing this issue at this time.
